export const ERROR_CODES = {
  AUTH_FAILED: 'AUTH_FAILED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INACTIVE_ACCOUNT: 'INACTIVE_ACCOUNT',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN'
};
